services:

  trinity.admin.menu_builder:
    class: Trinity\AdminBundle\Menu\MenuBuilder
    arguments:
      - "@event_dispatcher"
      - "@knp_menu.factory"
      - "@security.authorization_checker"


  trinity.admin.service.admin_manager:
    class: Trinity\AdminBundle\Service\AdminManager
    arguments:
      - "%trinity.admin.search_text%"
      - "%trinity.admin.app_version%"


  trinity.admin.type.froala_editor:
      class: Trinity\AdminBundle\Form\FroalaType\FroalaType
      arguments:
          - "%trinity.admin.froala_editor_settings%"
          - "@router"
      tags:
        - { name: form.type }


  trinity.twig.extensions.controller:
      class: Trinity\AdminBundle\Twig\ControllerActionExtension
      calls:
          - [setRequest, ["@?request="]]
      tags:
          - { name: twig.extension }