services:

  trinity.admin.menu_builder:
    class: Trinity\AdminBundle\Menu\MenuBuilder
    arguments: ["@event_dispatcher", "@knp_menu.factory", "@doctrine.orm.entity_manager", "@white_october_breadcrumbs", "@service_container"]


  trinity.admin.service.admin_manager:
    class: Trinity\AdminBundle\Service\AdminManager
    arguments:
      - "@service_container"


  trinity.twig.extension.side_bar:
      class: Trinity\AdminBundle\Twig\SidebarExtension
      arguments:  ["@router"]
      tags:
          - { name: twig.extension }


  trinity.twig.extensions.controller:
          class: Trinity\AdminBundle\Twig\ControllerActionExtension
          calls:
              - [setRequest, ["@?request="]]
          tags:
              - { name: twig.extension }