imports:
    - { resource: parameters.yml }
    - { resource: security.yml }


parameters:
    database_driver: pdo_sqlite
    database_host: 127.0.0.1
    database_port: 5432
    database_name: trinity
    database_user: tomas
    database_password: null
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_port: 25
    mailer_user: null
    mailer_password: null
    secret: ThisTokenIsNotSoSecretChangeIt
    debug_toolbar: true
    debug_redirects: false
    use_assetic_controller: true
    locale: en
    trinity.search.doctrine_prefix: "Grid"
    trinity.search.namespace: "Trinity\\Bundle\\GridBundle\\Tests\\Functional\\Entity"


web_profiler:
    toolbar: true
    intercept_redirects: true
    position: bottom


assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ TrinityAdminBundle ]
    filters:
        cssrewrite: ~
    assets:
         bowtie_css:
           inputs:
              - "%kernel.root_dir%/../vendor/modpreneur/bowtie/src/css/bowtie.css"
         necktie_icons:
           inputs:
              - "%kernel.root_dir%/../vendor/modpreneur/bowtie/administration/css/necktie-icons.css"
         ticones_eot:
           inputs:
              - "%kernel.root_dir%/../vendor/modpreneur/bowtie/src/fonts/tiecons/tiecons.eot"
           outpoutput: "fonts/tiecons/tiecons.eot"
         ticones_svg:
           inputs:
              - "%kernel.root_dir%/../vendor/modpreneur/bowtie/src/fonts/tiecons/tiecons.svg"
           output: "fonts/tiecons/tiecons.svg"
         ticones_ttf:
           inputs:
              - "%kernel.root_dir%/../vendor/modpreneur/bowtie/src/fonts/tiecons/tiecons.ttf"
           output: "fonts/tiecons/tiecons.ttf"
         ticones_woff:
           inputs:
              - "%kernel.root_dir%/../vendor/modpreneur/bowtie/src/fonts/tiecons/tiecons.woff"
           output: "fonts/tiecons/tiecons.woff"
         necktie_eot:
           inputs:
              - "%kernel.root_dir%/../vendor/modpreneur/bowtie/administration/fonts/necktie.eot"
           output: "fonts/necktie.eot"
         necktie_svg:
           inputs:
              - "%kernel.root_dir%/../vendor/modpreneur/bowtie/administration/fonts/necktie.svg"
           output: "fonts/necktie.svg"
         necktie_ttf:
           inputs:
              - "%kernel.root_dir%/../vendor/modpreneur/bowtie/administration/fonts/necktie.ttf"
           output: "fonts/necktie.ttf"
         necktie_woff:
           inputs:
              - "%kernel.root_dir%/../vendor/modpreneur/bowtie/administration/fonts/necktie.woff"
           output: "fonts/necktie.woff"

         trinity_eot:
            inputs:
              - "%kernel.root_dir%/../../src/AdminBundle/Resources/Public/fonts/trinity.eot"
            output: "fonts/trinity.eot"
         trinity_ttf:
            inputs:
              - "%kernel.root_dir%/../../src/AdminBundle/Resources/Public/fonts/trinity.ttf"
            output: "fonts/trinity.ttf"
         trinity_woff:
            inputs:
              - "%kernel.root_dir%/../../src/AdminBundle/Resources/Public/fonts/trinity.woff"
            output: "fonts/trinity.wof"
         trinity_svg:
            inputs:
              - "%kernel.root_dir%/../../src/AdminBundle/Resources/Public/fonts/trinity.svg"
            output: "fonts/trinity.svg"



framework:
    secret: "Three can keep a secret, if two of them are dead. MUHEHE."
    test: ~
    session:
        storage_id: session.storage.filesystem
    router: { resource: "%kernel.root_dir%/config/routing.yml" }
    templating:
            engines: ['twig']
    form: ~


# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

#Other bundle configs---------------------------------------------------------------------------------------------------


knp_menu:
    twig:
        template: knp_menu.html.twig
    templating: false
    default_renderer: twig


services: